- name: create fact
  set_fact:
    gitlab_repo_file_list: []
  when: gitlab_repo_file_list is not defined

- name: get the repository file tree
  uri:
    url: https://gitlab.com/api/v4/projects/{{ gitlab_project_id }}/repository/tree?ref=master&per_page=2&page={{ page_num }}
    body_format: json
    validate_certs: no
    status_code: 200
    return_content: yes
    headers:
      Private-Token: "{{ gitlab_access_token }}"
  register: response
  delegate_to: localhost
- name: save the file name
  set_fact:
    gitlab_repo_file_list: "{{ gitlab_repo_file_list }} + {{ response.json | json_query('[].name') }}"
- include_role:
    name: gitlab_tree
  vars:
    page_num: "{{ response.x_next_page }}"
  when: response.x_next_page
